### PR TITLE
Add development instructions for Polymer 3 convertion [skip ci]

### LINKED ISSUE #174: Update development instructions
Write P3 compliant instructions

https://github.com/vaadin/vaadin-core/blob/master/DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by platosha**
Fixes #174

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/175)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[DEVELOPMENT.md, line 84 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175#-L9OZ49LDW6uFCS3SEue:-L9OZ49LDW6uFCS3SEuf:bqd0d2h) ([raw file](https://github.com/vaadin/vaadin-core/blob/7c3b3bfa8222e8c186fb266fe27394a863db8087/DEVELOPMENT.md#L84)):*
> ```Markdown
> In order to use a Vaadin component in Polymer 3, the codebase has to
> be converted first. Follow these steps to convert a Vaadin component
> in your local repository:
> ```

The second sentence is not clear to me, I would simply in the way:

`Change to the directory of the Vaadin component you want to convert, and follow these steps:`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175#-L9OcFE61Y2aN807A4gS:-L9OcFE61Y2aN807A4gT:bqhfnnq) (no related file):*
Consider also adding some mention that unlike Polymer elements (which have auto generated branches), Polymer 3 versions of Vaadin components are only published to npm, not pushed to GitHub. Any proposed PRs should target master branch of component and P2 codebase.

---

*[DEVELOPMENT.md, line 107 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175#-L9Oc-A71Fi1Ke-sqoyC:-L9Oc-A71Fi1Ke-sqoyD:b-7gesny) ([raw file](https://github.com/vaadin/vaadin-core/blob/7c3b3bfa8222e8c186fb266fe27394a863db8087/DEVELOPMENT.md#L107)):*
> ```Markdown
> 
> # Run development server
> $ polymer serve pols --npm --module-resolution node --open
> ```

what is "pols"? was it your personal shortcut?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175)*

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175#-L9OcFE61Y2aN807A4gS:-L9P3NgLE2PkNlO-V5Zi:bwqa9fa) (no related file):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Consider also adding some mention that unlike Polymer elements (which have auto generated branches), Polymer 3 versions of Vaadin components are only published to npm, not pushed to GitHub. Any proposed PRs should target master branch of component and P2 codebase.
</blockquote></details>

Good suggestion, done.

---

*[DEVELOPMENT.md, line 84 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175#-L9OZ49LDW6uFCS3SEue:-L9P3PE5CIbMcsXylMXe:br0bztg) ([raw file](https://github.com/vaadin/vaadin-core/blob/7c3b3bfa8222e8c186fb266fe27394a863db8087/DEVELOPMENT.md#L84)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The second sentence is not clear to me, I would simply in the way:

`Change to the directory of the Vaadin component you want to convert, and follow these steps:`
</blockquote></details>

Better now?

---

*[DEVELOPMENT.md, line 107 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175#-L9Oc-A71Fi1Ke-sqoyC:-L9P3VPlE0csOaVYfITh:bye1r3f) ([raw file](https://github.com/vaadin/vaadin-core/blob/7c3b3bfa8222e8c186fb266fe27394a863db8087/DEVELOPMENT.md#L107)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

what is "pols"? was it your personal shortcut?
</blockquote></details>

oops, yes. Removed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DEVELOPMENT.md, line 84 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175#-L9OZ49LDW6uFCS3SEue:-L9QcZKC6krY2Gl-NpCa:b2nign3) ([raw file](https://github.com/vaadin/vaadin-core/blob/7c3b3bfa8222e8c186fb266fe27394a863db8087/DEVELOPMENT.md#L84)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Better now?
</blockquote></details>

yep

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175#-:-L9Qcd-wDqDXRD29FEZf:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-core/175)*

**Pull request merged**
