### PR TITLE
Update to latest stable versions

### PR DESCRIPTION
**Pull request by YuriyVaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/180)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/180#-:-LB0vZcF9DtRDFzhvjH2:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-core/180#-LBK-ZYZA8dQtGh7XEW1:-LBK-ZYZA8dQtGh7XEW2:bk8ni3g) (no related file):*
Can and should we change to hat dependencies (`^.x.0.0`) so that maintenance releases are automatically in?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/180)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-core/180#-LBK-ZYZA8dQtGh7XEW1:-LBKOzCj3IdymV43iVvS:bldqvxo) (no related file):*
> Can and should we change to hat dependencies (^.x.0.0) so that maintenance releases are automatically in?

I asked the Platform Team members about this, will post their replies here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/180)*

**Comment by limonte** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-core/180#-LBK-ZYZA8dQtGh7XEW1:-LBL37sABSJKeFwHfJ4L:b-oa30q6) (no related file):*
> I asked the Platform Team members about this, will post their replies here.

From https://vaadin.slack.com/messages/CACKS4075/convo/CACKS4075-1525072383.000146/

> Risto Yrjänä
> Talked with Pekka. Let’s stick with the fixed versions, since the WebJAR’s have to be in sync.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/180)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-core/180#-LBK-ZYZA8dQtGh7XEW1:-LBLCoLYC-N0evX_ASh8:b-9uggnx) (no related file):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> I asked the Platform Team members about this, will post their replies here.

From https://vaadin.slack.com/messages/CACKS4075/convo/CACKS4075-1525072383.000146/

> Risto Yrjänä
> Talked with Pekka. Let’s stick with the fixed versions, since the WebJAR’s have to be in sync.
</blockquote></details>

Fine. In that case please double check that this is up-to-date. The grid has v5.0.3 already, for example.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/180)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-core/180#-LBK-ZYZA8dQtGh7XEW1:-LBLTKsjE1XO72EQMx_-:bjg4zk8) (no related file):*
> Fine. In that case please double check that this is up-to-date. The grid has v5.0.3 already, for example.

grid was the only one not-up-to-date, updated now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/180)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/180)*

**Pull request merged**
