### PR TITLE
Update dependencies to Lumo versions

### LINKED ISSUE #147: Imports `vaadin-ordered-layout.html` even tough it does not exist
`vaadin-core.html` imports `vaadin-ordered-layout.html` even tough it does not exist.

https://github.com/vaadin/vaadin-core/blob/master/vaadin-core.html#L10

### LINKED ISSUE #151: Expecting `vaadin-core.html` to import all "sub" elements too
I imported `vaadin-core.html` and used `<vaadin-form-layout>` (worked). But then copied `<vaadin-form-item>` from the form-layout's docs and expected it to work. Took me a while to realize that it wasn't imported at all. So as a user I was under the expectation that `vaadin-core.html` really imports all the elements.

### PR DESCRIPTION
**Pull request by web-padawan**
Also aligned imports in `vaadin-core.html`

Fixes #147 
Fixes #151

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-core/161)

### CODE REVIEW

**Comment by platosha** [comment]
Not sure if it’s expected to contain every public bundled element.

If so, then it is still missing `vaadin-combo-box-light.html`, `vaadin-date-picker-light.html`, and lots of stuff from `vaadin-grid/all-imports.html`...

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2dwLk5dsHeFH8tgdpS:br2c8ne)*

**Comment by tomivirkki** [comment]
`vaadin-tab.html` also

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2dxKgO-mk39IIcOO0S:b6lzy96)*

**Comment by web-padawan** [comment]
Added `vaadin-tab.html` 

@platosha about the `light` versions and the rest of grid stuff: those elements do not implement version getter and are not "first-class sitizens". So I think that doesn't make much sense to include them here.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2dxg4WHmWx0uQ-ohfQ:b3z4bnt)*

**Comment by platosha** [comment]
@web-padawan from the issue #151 I assume it’s expected that all sub elements are available for users right away, regardless of their citizenship class. `<vaadin-grid>`’s users might expect `<vaadin-grid-sorter>` to work, and so on, likewise `<vaadin-form-layout>`’s users expect `<vaadin-form-item>` to work.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2e6-v1aAPx_sBGei7D:b-790bih)*

**Comment by platosha** [comment]
I don’t see why exactly `<vaadin-form-item>` is first class and `<vaadin-grid-sorter>` is second class. Both of them are helper elements to support some features / use cases of the main element. In general, `<vaadin-form-item>` is not required to use `<vaadin-form-layout>`, same as `<vaadin-grid-sorter>` is not required by `<vaadin-grid>`.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2e7bOBmIRNNbotEqCn:ba3tvtl)*

**Comment by web-padawan** [comment]
I agree that it makes sense to import optional elements here as well. @tomivirkki WDYT?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2sr6FpqWnK2ZMNiS8Y:b-o1mf6m)*

**Comment by tomivirkki** [comment]
Makes sense, yeah

**Comment by web-padawan** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2t0bkXoTcr6atD-6qS:b-896fix)*

**Comment by vicsstar** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2tar2Cv_JB4ilcVB-x:bnfp4nl)*

**Comment by vicsstar** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-core/161#-:-L2xq8flvuoTUOfKRX7q:bnfp4nl)*

**Pull request merged**
